version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  backend:
    command:
      - gunicorn --bind 0.0.0.0:8000 backend.wsgi
    env_file:
      - .env
    image: cruvadio/foodgram_backend:latest
    volumes:
      - ./backend/:/app/
      - static:/backend_static
      - media:/media
      - ./data:/app/data
    depends_on:
      db:
        condition: service_started
      frontend:
        condition: service_completed_successfully

  frontend:
    env_file:
      - .env
    image: cruvadio/foodgram_frontend:latest
    volumes:
      - static:/static
  nginx:
    image: cruvadio/foodgram_gateway:latest
    env_file:
      - .env
    ports:
      - "9090:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_completed_successfully
